In [1]:
import BJ_RL
import BJ_NEAT_TEST
import numpy as np
from DQN import DQN
from Condition_method import Condition
from keras.utils.np_utils import to_categorical

pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html


Using TensorFlow backend.



Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
game = BJ_NEAT_TEST

In [3]:
game.main()
game.runGame()
game.gameBoard
observation = state2catagory(game.gameBoard)
observation.shape

NameError: name 'state2catagory' is not defined

In [13]:
def state2catagory(observation):
    observation = np.array(observation)
    observation = np.concatenate(observation[:])
    observation  = to_categorical(observation, num_classes=7)
    # observation = observation.reshape(1,observation.shape[0],observation.shape[1])
    observation = observation.reshape(observation.shape[0]*observation.shape[1])
    return observation

In [12]:
m = Condition()
m.action(game.getBlankBoard())

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [102]:
temp = np.zeros(8)
temp[4]= 1
temp[np.newaxis,:]

(1, 8)

In [20]:
p1, p2 = ((4, 5), (4, 6))
p1[0] - p2[0]

0

In [ ]:
game.getBlankBoard()

In [4]:
RL = DQN(game.getBlankBoard(),[64,2])

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
                Model loaded


In [19]:
d = RL.state2catagory(game.getBlankBoard())
dd = []
for _ in range(10):
    dd.append(d[0,:])
dd = np.array(dd)

q_next = RL.model1.predict(dd)
np.max(q_next, axis=1)* 0.9 + np.array([1,2,3,4,5,6,7,8,9,10])
# q_next.shape
batch_index = np.arange(10, dtype=np.int32)
np.argmax(q_next, axis=1).astype(int)

array([56, 56, 56, 56, 56, 56, 56, 56, 56, 56])

In [18]:
q_next[batch_index,np.argmax(q_next, axis=1)] 

array([ 1.4106408,  2.410641 ,  3.410641 ,  4.4106407,  5.4106407,
        6.4106407,  7.4106407,  8.410641 ,  9.410641 , 10.410641 ],
      dtype=float32)

In [20]:
q_next[batch_index,np.argmax(q_next, axis=1).astype(int)] = np.max(q_next, axis=1)* 0.9 + np.array([1,2,3,4,5,6,7,8,9,10])

In [5]:
game.main()

                Model loaded


C:\Users\User\Anaconda3\envs\Sgan\lib\site-packages\keras\engine\saving.py:341: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '


episode: 0
Final score:  30
Continuously make 30 mistakes
episode: 1
Final score:  0
Continuously make 30 mistakes
episode: 2
Final score:  0
Continuously make 30 mistakes
episode: 3
Final score:  10
Continuously make 30 mistakes
episode: 4
Final score:  0
Continuously make 30 mistakes
episode: 5
Final score:  0
Continuously make 30 mistakes
episode: 6
Final score:  0
Continuously make 30 mistakes
episode: 7
Final score:  20
Continuously make 30 mistakes
episode: 8
Final score:  0
Continuously make 30 mistakes
episode: 9
Final score:  50
Continuously make 30 mistakes
episode: 10


KeyboardInterrupt: 

In [8]:

def stack_samples(samples):
	array = np.array(samples)
	
	current_states = np.stack(array[:,0]).reshape((np.stack(array[:,0]).shape))
	actions = np.stack(array[:,1]).reshape((array.shape[0],-1))
	rewards = np.stack(array[:,2]).reshape((array.shape[0],-1))
	new_states = np.stack(array[:,3]).reshape((np.stack(array[:,3]).shape))
	dones = np.stack(array[:,4]).reshape((array.shape[0],-1))
	
	return current_states, actions, rewards, new_states, dones
stack_samples(game.RL.samples)[0].shape

(400, 1, 448)

In [9]:
game.RL.samples

[[array([[0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
          0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
          0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
          0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
          1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
          1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
          0., 0., 0., 0., 1., 0., 0., 

In [384]:

from keras.models import Sequential, Model, load_model
from keras.layers import Dense, Dropout, Input, Conv2D, LeakyReLU, Flatten
from keras.layers.merge import Add, Concatenate
from keras.optimizers import Adam

state_input = Input(shape=(448,))
h1 = Dense(500, activation='relu')(state_input)
h2 = Dense(100, activation='relu')(h1)
h3 = Dense(10, activation='relu')(h2)

output1 = Dense(64, activation='softmax')(h3)
output2 = Dense(4, activation='softmax')(h3)

output    = Concatenate()([output1, output2])

model = Model(state_input, merged)

ValueError: Unknown activation function:leakyrelu

In [5]:
model.summary()

Model: "model_2"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            (None, 448)          0                                            
__________________________________________________________________________________________________
dense_5 (Dense)                 (None, 500)          224500      input_2[0][0]                    
__________________________________________________________________________________________________
dense_6 (Dense)                 (None, 100)          50100       dense_5[0][0]                    
__________________________________________________________________________________________________
dense_7 (Dense)                 (None, 10)           1010        dense_6[0][0]                    
____________________________________________________________________________________________

In [12]:
temp = []
# for i in range(len(cur_state)):
temp.append([np.random.random(),np.random.random()])
np.array(temp).shape

(1, 2)

In [19]:
np.random.random(68)[np.newaxis,:]

array([[0.31494733, 0.95463611, 0.59833432, 0.97626936, 0.41014703,
        0.43972624, 0.60021977, 0.33692261, 0.83465781, 0.37882813,
        0.12347063, 0.73920238, 0.53503401, 0.58015491, 0.89402117,
        0.83031614, 0.66299559, 0.29687759, 0.12209984, 0.17473743,
        0.99415239, 0.88836629, 0.19297662, 0.86904333, 0.38248103,
        0.29345635, 0.83900165, 0.19389117, 0.39470761, 0.04439285,
        0.08699495, 0.21474622, 0.97337206, 0.89796772, 0.83922345,
        0.33743484, 0.40285976, 0.46851751, 0.71535271, 0.11931257,
        0.80602427, 0.6247286 , 0.1053554 , 0.79768485, 0.96467696,
        0.11997788, 0.00504613, 0.78668839, 0.59643222, 0.40021381,
        0.85398721, 0.62200534, 0.64771907, 0.57134493, 0.91906391,
        0.32206697, 0.41541721, 0.90035026, 0.51738955, 0.60587973,
        0.93895357, 0.51709462, 0.54651189, 0.49085713, 0.44180187,
        0.83919364, 0.82559369, 0.42285487]])

In [21]:
y =0.9

In [26]:

y *= .99999995
y

0.5913420427781318

In [7]:
observation = game.cur
observation

[[0, 3, 1, 3, 5, 2, 6, 5],
 [6, 5, 3, 2, 4, 1, 5, 2],
 [0, 3, 4, 1, 0, 5, 4, 6],
 [6, 5, 6, 4, 5, 1, 6, 1],
 [4, 2, 4, 0, 3, 4, 1, 2],
 [1, 6, 0, 6, 0, 5, 2, 6],
 [2, 0, 2, 4, 3, 0, 5, 3],
 [6, 1, 5, 3, 5, 6, 3, 4]]

In [10]:
from keras.utils.np_utils import to_categorical
observation = game.cur
observation = np.array(observation)
# observation = np.concatenate(observation[:])
observation  = to_categorical(observation, num_classes=7)
# observation = observation.reshape(1,observation.shape[0],observation.shape[1])
observation.shape

(8, 8, 7)

In [75]:
int(63.99999999999999)

63

In [6]:
import numpy as np
g = np.array((-0.07644529,
         -0.07644529,
         -0.01306832,
         -0.07644529,
         -0.01306832,
         -0.07644529,
         -0.01306832,
         -0.01306832,
         -0.07644529,
         -0.01306832,
         -0.01306832,
         -0.01306832,
         -0.07644529,
         -0.07644529,
         -0.01306832,
         -0.07644529,
         -0.07644529,
         -0.07644529,
         -0.01306832,
         -0.01306832))[:,np.newaxis] *0.9
g.shape

(1, 20)

In [70]:
np.float64((np.ones(20)[:,np.newaxis]))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [85]:
#!/usr/bin/env python

'''
Features:
number of valid pairs in state
number in a row produced by switched: testSwitch
max count of a number in a row: maxCount[0]
Max count of a number in a col: maxCount[1]
'''

import random
import numpy as np
import collections

NSARSA = 100       # number of SARS' sequences to generate at each turn
NUMSAMPLES = 10000    # number of total trials to run
NTURNS = 5        # number of turns in the game
NROWS = 8        
NCOLS = 8
NCOLORS = 5
DISCOUNT = 0.5        # discount in computing Q_opt
STEP_SIZE = 0.0001        # eta in computing Q_opt
EPSILON = 0.2        # epsilon in epsilon-greedy (used in generating SARS')
# SCORE(X) = 10(X^2 - X)
weights = np.zeros(4, dtype = float)

def dotProd(a,b):
    return sum(a[i]*b[i] for i in range(len(a)))

def arrToTuple(arr):
    tupArr = [tuple(elem) for elem in arr]
    return tuple(tupArr)

def isEndState(state):
    return state[1] == 0

def actions(state):
    actions = []
    grid = state[0]
    for i in range(NROWS):
        for j in range(NCOLS):
            if isValidMove(grid,(i,j),(i,j+1)):
                coord1 = (i,j)
                coord2 = (i,j+1)
                actions.append((coord1, coord2))
            elif isValidMove(grid,(i,j),(i+1,j)):
                coord1 = (i,j)
                coord2 = (i+1,j)
                actions.append((coord1, coord2))
    return actions



def dropCols(grid, colsToRowsMap):
    for col in colsToRowsMap:
        currRows = colsToRowsMap[col]
        minRow = currRows[0]
        maxRow = currRows[1]
        diff = maxRow - minRow + 1
        for i in range(minRow):
            grid[minRow-1-i+diff, col] = grid[minRow-1-i, col]
        for i in range(diff):
            grid[i, col] = random.randint(1, NCOLORS)
    return

def exploreCoord(grid, i, j):
    color = grid[i, j]
    colorRowsSet = set([(i, j)])
    colorColsSet = set([(i, j)])
    #explore above
    for row in range(i):
        if color != grid[i-row-1, j]:
            break
        colorRowsSet.add((i-row-1, j))
    #explore below
    for row in range(i+1, NROWS):
        if color != grid[row, j]:
            break
        colorRowsSet.add((row, j))
    #explore left
    for col in range(j):
        if color != grid[i, j-col-1]:
            break
        colorColsSet.add((i, j-col-1))
    #explore right
    for col in range(j+1, NCOLS):
        if color != grid[i, col]:
            break
        colorColsSet.add((i, col))
    return colorRowsSet, colorColsSet

def cascadeCoords(grid):
    coords = set()
    for i in range(NROWS):
        for j in range(NCOLS):
            colorRowsSet, colorColsSet = exploreCoord(grid, i, j)
            colorAllSet = set()
            if len(colorRowsSet) >= 3:
                colorAllSet = colorRowsSet
            if len(colorColsSet) >= 3:
                colorAllSet = colorAllSet.union(colorColsSet)
            if len(colorAllSet) > len(coords):
                coords = colorAllSet
    return coords

def cascade(grid):
    turnScore = 0
    combo = 1
    while (True):
        coords = cascadeCoords(grid)
        cascadeSize = len(coords)
        if cascadeSize < 3:
            break        
        addScore = 10*(cascadeSize**2-cascadeSize)*combo
        turnScore += addScore
        combo += 1
        colsToRowsMap = {}
        for coord in coords:
            if coord[1] not in colsToRowsMap:
                colsToRowsMap[coord[1]] = [coord[0], coord[0]]
            else:
                currRows = colsToRowsMap[coord[1]]
                currRowMin = currRows[0]
                currRowMax = currRows[1]
                if coord[0] < currRowMin:
                    currRows[0] = coord[0]
                elif coord[0] > currRowMax:
                    currRows[1] = coord[0]
        dropCols(grid, colsToRowsMap)
        # if True:
        if False:
            print (coords)            
            print ('deleted', cascadeSize, 'positions')
            print (grid)
            print (addScore)
    return grid, turnScore            

def testSwitch(state, action):
    grid = np.array(state[0])
    coord1, coord2 = action
    grid[coord1], grid[coord2] = grid[coord2], grid[coord1]
    coords = cascadeCoords(grid)
    return len(coords)

def maxCount(state):
    grid = np.array(state[0])
    rowCount = collections.Counter()
    colCount = collections.Counter()
    for i in range(NROWS):
        for j in range(NCOLS):
            rowCount[(i, grid[i,j])] += 1
            colCount[(j, grid[i,j])] += 1
    max_row = rowCount.most_common(1)[0][1] 
    max_col = colCount.most_common(1)[0][1]
    return max_row, max_col


def initialize(grid):
    for i in range(NROWS):
        for j in range(NCOLS):
            grid[i, j] = random.randint(1, NCOLORS)    
    print (grid)
    grid, turnScore = cascade(grid)
    return grid

def isValidCoord(coord):
    if (coord[0] < 0 or coord[0] >= NROWS) or (coord[1] < 0 or coord[1] >= NCOLS):
        return False
    else:
        return True

def isValidMove(grid,coord1,coord2):
    #coord is (x,y)
    if coord1 == coord2:
        return False
    if isValidCoord(coord1) and isValidCoord(coord2):
        if (abs(coord1[0] - coord2[0]) == 1 and coord1[1] == coord2[1]) or (abs(coord1[1] - coord2[1]) == 1 and coord1[0] == coord2[0]):
            gridCopy = np.copy(grid)
            gridCopy[coord1], gridCopy[coord2] = gridCopy[coord2], gridCopy[coord1]
            colorRowsSet1, colorColsSet1 = exploreCoord(gridCopy, coord1[0], coord1[1])
            if len(colorRowsSet1) >= 3 or len(colorColsSet1) >= 3:
                return True
            colorRowsSet2, colorColsSet2 = exploreCoord(gridCopy, coord2[0], coord2[1])            
            if len(colorRowsSet2) >= 3 or len(colorColsSet2) >= 3:
                return True
    return False

def numValidMoves(grid):
    count = 0
    for i in range(NROWS):
        for j in range(NCOLS):
            if isValidMove(grid,(i,j),(i,j+1)) or isValidMove(grid,(i,j),(i+1,j)):
                count += 1
    return count

def validMoveExists(grid):
    for i in range(NROWS):
        for j in range(NCOLS):
            if isValidMove(grid,(i,j),(i,j+1)) or isValidMove(grid,(i,j),(i+1,j)):
                return True
    return False

def makeSwitch(state, action):
    grid = np.array(state[0])
    coord1, coord2 = action
    grid[coord1], grid[coord2] = grid[coord2], grid[coord1]
    grid, turnScore = cascade(grid)
    return grid, turnScore

def getFeatureVec(state, action):
    nValidMoves = numValidMoves(state[0])
    maxDelete = testSwitch(state, action)
    maxRowCount, maxColCount = maxCount(state)
    phi = [nValidMoves, maxDelete, maxRowCount, maxColCount]
    return np.array(phi) 

def getQopt(state, action):
    if isEndState(state): return 0.
    return dotProd(getFeatureVec(state, action), weights)

def generateSARSA(currState):
    sarsa = []
    prevState = currState
    while (not isEndState(prevState)):
        action = None
        if (random.random() < EPSILON):
            action = random.choice(actions(prevState))
        else:
            Vopt, action = max((getQopt(prevState, action), action) for action in actions(prevState))
            print(Vopt, action)
        grid, reward = makeSwitch(prevState, action)
        newState = (arrToTuple(grid), prevState[1]-1)
        sarsa.append((prevState, action, reward, newState))
        prevState = newState
    return sarsa

# def updateQ(state, action, reward, newState):
#     Vopt, pi_opt = max((Qopt[(newState, action)], action) for action in actions(newState))
#     Qopt[(state, action)] = (1-STEP_SIZE)*Qopt[(state, action)] + STEP_SIZE*(reward + DISCOUNT*Vopt)
#     updated.add(state)
#     return

def updateWeights(state, action, reward, newState):
    global weights
    Vopt, pi_opt = max((getQopt(newState, action), action) for action in actions(newState))
    weights = weights - STEP_SIZE * (getQopt(state, action) - (reward + DISCOUNT*Vopt)) * getFeatureVec(state, action)
    return

def aiPlay(grid, sample):
    score = 0
    for turn in range(NTURNS):            
        while True:
            if validMoveExists(grid):
                break
            grid = np.resize((1,NROWS*NCOLS))
            np.random.shuffle(grid)
            grid = np.resize((NROWS, NCOLS))
        turnsLeft = NTURNS - turn
        print ('')    
        print ('Turns left:', NTURNS - turn)
        print ('SCORE', score)
        print (grid    )
        print ('generating SARSA...')
        currState = (arrToTuple(grid), turnsLeft)
        sarsa = [generateSARSA(currState) for i in range(NSARSA)]    
        print ('updating weights')
        for i in range(NSARSA):
            for (state, action, reward, newState) in sarsa[i]:
                updateWeights(state, action, reward, newState)
        print ('new weights:', weights)
        print ('obtaining optimal action...')
        Vopt, pi_opt = max((getQopt(currState, action), action) for action in actions(currState))
        action = pi_opt
        print ('switched', action[0], 'and', action[1])
        grid, turnScore = makeSwitch(currState, action)
        score += turnScore
    print ('')        
    print ('Turns left:', 0)
    print( grid    )
    print (sample, 'FINAL SCORE', score)
    return score

def main():
    random.seed()
    np.random.seed()
    scoreSum = 0
    for i in range(NUMSAMPLES):
        grid = np.zeros((NROWS, NCOLS), dtype = int)
        grid = initialize(grid)
        score = aiPlay(grid, i+1)
        scoreSum += score
        print (i+1, 'AVERAGE SCORE:', float(scoreSum)/(i+1))
        print ('')
    return

# if __name__ == "__main__":
#     main()

In [90]:
grid = np.zeros((NROWS, NCOLS), dtype = int)
grid = initialize(grid)


[[3 5 4 5 2 3 2 2]
 [3 2 1 2 4 1 1 1]
 [1 5 1 3 5 3 2 3]
 [2 5 1 2 2 2 2 1]
 [1 5 3 4 5 3 3 1]
 [5 5 3 4 3 1 2 3]
 [4 2 3 5 2 4 3 5]
 [2 4 1 1 4 4 5 4]]


In [91]:
currState = (arrToTuple(grid),7)
currState

(((3, 1, 2, 4, 5, 2, 4, 2),
  (3, 5, 4, 5, 2, 3, 2, 1),
  (1, 4, 5, 2, 4, 1, 1, 3),
  (2, 3, 2, 3, 5, 3, 2, 1),
  (1, 5, 4, 4, 5, 3, 3, 1),
  (5, 2, 1, 4, 3, 1, 2, 3),
  (4, 2, 4, 5, 2, 4, 3, 5),
  (2, 4, 1, 1, 4, 4, 5, 4)),
 7)

In [92]:
generateSARSA(currState)

0.0 ((7, 6), (7, 7))
0.0 ((7, 0), (7, 1))
0.0 ((5, 6), (5, 7))
0.0 ((6, 6), (6, 7))
0.0 ((6, 5), (7, 5))


[((((3, 1, 2, 4, 5, 2, 4, 2),
    (3, 5, 4, 5, 2, 3, 2, 1),
    (1, 4, 5, 2, 4, 1, 1, 3),
    (2, 3, 2, 3, 5, 3, 2, 1),
    (1, 5, 4, 4, 5, 3, 3, 1),
    (5, 2, 1, 4, 3, 1, 2, 3),
    (4, 2, 4, 5, 2, 4, 3, 5),
    (2, 4, 1, 1, 4, 4, 5, 4)),
   7),
  ((4, 4), (5, 4)),
  1680,
  (((3, 2, 4, 1, 4, 1, 1, 4),
    (3, 1, 3, 1, 4, 5, 4, 2),
    (1, 5, 2, 4, 1, 1, 2, 1),
    (2, 3, 2, 3, 4, 5, 1, 3),
    (1, 5, 4, 4, 5, 2, 5, 1),
    (5, 2, 1, 4, 5, 1, 4, 3),
    (4, 2, 4, 5, 2, 4, 3, 5),
    (2, 4, 1, 1, 4, 4, 5, 4)),
   6)),
 ((((3, 2, 4, 1, 4, 1, 1, 4),
    (3, 1, 3, 1, 4, 5, 4, 2),
    (1, 5, 2, 4, 1, 1, 2, 1),
    (2, 3, 2, 3, 4, 5, 1, 3),
    (1, 5, 4, 4, 5, 2, 5, 1),
    (5, 2, 1, 4, 5, 1, 4, 3),
    (4, 2, 4, 5, 2, 4, 3, 5),
    (2, 4, 1, 1, 4, 4, 5, 4)),
   6),
  ((7, 6), (7, 7)),
  780,
  (((3, 2, 2, 4, 2, 5, 1, 4),
    (3, 1, 4, 3, 3, 2, 3, 2),
    (1, 5, 3, 1, 1, 5, 4, 1),
    (2, 3, 2, 4, 5, 1, 2, 3),
    (1, 5, 2, 3, 1, 5, 1, 1),
    (5, 2, 1, 4, 5, 2, 5, 3),
    (4, 2, 4, 5, 5, 

In [1826]:
#!/usr/bin/env python

'''
Features:
1.     + min row
2.     + max row
3.     + same col switch?
4.     + num valid moves
5.     + num in a row from making switch
6.     + median utility from NSARS episodes with limited DEPTH
7-15.  + max count of any 1 color in rows 1-9
16-24. + max count of any 1 color in cols 1-9
'''

import random
import numpy as np
import collections
from sklearn.neural_network import MLPRegressor

net = MLPRegressor(hidden_layer_sizes=(10,))
net.fit([[0] * 22], [0])

# NSCORES = 100
NFEATURES = 24
NSARS = 25       # number of SARS' sequences to generate at each turn
DEPTH = 5 	#max depth of SARS' sequence
NUMSAMPLES = 10000	# number of total trials to run
NTURNS = 50		# number of turns in the game
NROWS = 8
NCOLS = 8
NCOLORS = 5
DISCOUNT = 0.5		# discount in computing Q_opt
STEP_SIZE = 0.00000000001		# eta in computing Q_opt
EPSILON = 0.5		# epsilon in epsilon-greedy (used in generating SARS')
# SCORE(X) = 10(X^2 - X)
# weights = np.zeros(NFEATURES, dtype = float)



# inputs = Input(shape=(len(22),))
# x = Dense(4000, activation='relu')(inputs)
# x = Dropout(.25)(x)
# x = Dense(1000, activation='relu')(x)
# x = Dropout(.25)(x)
# x = Dense(250, activation='relu')(x)
# x = Dropout(.25)(x)
# x = Dense(50, activation='relu')(x)
# x = Dropout(.25)(x)
# outputs = Dense(1)(x)
# net = Model(inputs, outputs)
# a = Adam(lr = 0.001)
# net.compile(loss='mean_squared_error', optimizer=a, metrics=['accuracy'])


def dotProd(a,b):
    return sum(a[i]*b[i] for i in range(len(a)))

def arrToTuple(arr):
    tupArr = [tuple(elem) for elem in arr]
    return tuple(tupArr)

def isEndState(state):
    return state[1] == 0

def actions(state):
    actions = []
    grid = state[0]
    for i in range(NROWS):
        for j in range(NCOLS):
            if isValidMove(grid,(i,j),(i,j+1)):
                coord1 = (i,j)
                coord2 = (i,j+1)
                actions.append((coord1, coord2))
            elif isValidMove(grid,(i,j),(i+1,j)):
                coord1 = (i,j)
                coord2 = (i+1,j)
                actions.append((coord1, coord2))
    return actions

def dropCols(grid, colsToRowsMap):
    for col in colsToRowsMap:
        currRows = colsToRowsMap[col]
        minRow = currRows[0]
        maxRow = currRows[1]
        diff = maxRow - minRow + 1
        for i in range(minRow):
            grid[minRow-1-i+diff, col] = grid[minRow-1-i, col]
        for i in range(diff):
            grid[i, col] = random.randint(1, NCOLORS)
    return

def exploreCoord(grid, i, j):
    color = grid[i, j]
    colorRowsSet = set([(i, j)])
    colorColsSet = set([(i, j)])
    #explore above
    for row in range(i):
        if color != grid[i-row-1, j]:
            break
        colorRowsSet.add((i-row-1, j))
    #explore below
    for row in range(i+1, NROWS):
        if color != grid[row, j]:
            break
        colorRowsSet.add((row, j))
    #explore left
    for col in range(j):
        if color != grid[i, j-col-1]:
            break
        colorColsSet.add((i, j-col-1))
    #explore right
    for col in range(j+1, NCOLS):
        if color != grid[i, col]:
            break
        colorColsSet.add((i, col))
    return colorRowsSet, colorColsSet

def cascadeCoords(grid):
    coords = set()
    for i in range(NROWS):
        for j in range(NCOLS):
            colorRowsSet, colorColsSet = exploreCoord(grid, i, j)
            colorAllSet = set()
            if len(colorRowsSet) >= 3:
                colorAllSet = colorRowsSet
            if len(colorColsSet) >= 3:
                colorAllSet = colorAllSet.union(colorColsSet)
            if len(colorAllSet) > len(coords):
                coords = colorAllSet
    return coords

def cascade(grid):
    turnScore = 0
    combo = 1
    while (True):
        coords = cascadeCoords(grid)
        cascadeSize = len(coords)
        if cascadeSize < 3:
            break
        addScore = 10*(cascadeSize**2-cascadeSize)*combo
        turnScore += addScore
        combo += 1
        colsToRowsMap = {}
        for coord in coords:
            if coord[1] not in colsToRowsMap:
                colsToRowsMap[coord[1]] = [coord[0], coord[0]]
            else:
                currRows = colsToRowsMap[coord[1]]
                currRowMin = currRows[0]
                currRowMax = currRows[1]
                if coord[0] < currRowMin:
                    currRows[0] = coord[0]
                elif coord[0] > currRowMax:
                    currRows[1] = coord[0]
        dropCols(grid, colsToRowsMap)
        # if True:
        if False:
            print (coords)
            print ('deleted', cascadeSize, 'positions')
            print (grid)
            print (addScore)
    return grid, turnScore

def testSwitch(state, action):
    grid = np.array(state[0])
    coord1, coord2 = action
    grid[coord1], grid[coord2] = grid[coord2], grid[coord1]
    coords = cascadeCoords(grid)
    return len(coords)

def maxCount(state):
    grid = np.array(state[0])
    rowCount = collections.Counter()
    colCount = collections.Counter()
    max_row = []
    max_col = []
    colors = ['01','02','03','04','05','06','07','08','']
    for i in range(NROWS):
        for j in range(NCOLS):
            rowCount[(i, grid[i,j])] += 1
#         print(rowCount)
        max_row.append(max(rowCount[(i, color)] for color in range(1, NCOLORS)))
    for j in range(NCOLS):
        for i in range(NROWS):
            colCount[(j, grid[i,j])] += 1
        max_col.append(max(colCount[(j, color)] for color in range(1, NCOLORS)))
    return max_row + max_col

def initialize(grid):
    icon = ['/','O','X','@','$','&','%']
    for i in range(NROWS):
        for j in range(NCOLS):
            grid[i, j] = random.randint(1, NCOLORS)
    print (grid)
    grid, turnScore = cascade(grid)
    return grid

def isValidCoord(coord):
    if (coord[0] < 0 or coord[0] >= NROWS) or (coord[1] < 0 or coord[1] >= NCOLS):
        return False
    else:
        return True

def isValidMove(grid,coord1,coord2):
    #coord is (x,y)
    if coord1 == coord2:
        return False
    if isValidCoord(coord1) and isValidCoord(coord2):
        if (abs(coord1[0] - coord2[0]) == 1 and coord1[1] == coord2[1]) or (abs(coord1[1] - coord2[1]) == 1 and coord1[0] == coord2[0]):
            gridCopy = np.copy(grid)
            gridCopy[coord1], gridCopy[coord2] = gridCopy[coord2], gridCopy[coord1]
            colorRowsSet1, colorColsSet1 = exploreCoord(gridCopy, coord1[0], coord1[1])
            if len(colorRowsSet1) >= 3 or len(colorColsSet1) >= 3:
                return True
            colorRowsSet2, colorColsSet2 = exploreCoord(gridCopy, coord2[0], coord2[1])
            if len(colorRowsSet2) >= 3 or len(colorColsSet2) >= 3:
                return True
    return False

def numValidMoves(grid):
    count = 0
    for i in range(NROWS):
        for j in range(NCOLS):
            if isValidMove(grid,(i,j),(i,j+1)) or isValidMove(grid,(i,j),(i+1,j)):
                count += 1
    return count

def validMoveExists(grid):
    for i in range(NROWS):
        for j in range(NCOLS):
            if isValidMove(grid,(i,j),(i,j+1)) or isValidMove(grid,(i,j),(i+1,j)):
                return True
    return False

def makeSwitch(state, action):
    grid = np.array(state[0])
    coord1, coord2 = action
    grid[coord1], grid[coord2] = grid[coord2], grid[coord1]
    grid, turnScore = cascade(grid)
    return grid, turnScore

def generateSARSA(currState, action):
    prevState = currState
    depth = DEPTH
    utility = 0
    depth = 0
    while ((not isEndState(prevState)) and depth < DEPTH):
        if depth != 0:
            action = random.choice(actions(prevState))
        grid, reward = makeSwitch(prevState, action)
        newState = (arrToTuple(grid), prevState[1]-1)
        prevState = newState
        utility += reward * (DISCOUNT**depth)
        depth += 1
    return utility

def getFeatureVec(state, action):
    minRow = min(action[0][0], action[1][0])
    maxRow = max(action[0][0], action[1][0])
    sameCol = 1 if action[0][1] == action[1][1] else 0
    nValidMoves = numValidMoves(state[0])
    maxDelete = testSwitch(state, action)
    medUtil = np.median([generateSARSA(state, action) for i in range(NSARS)])
    phi = [minRow, maxRow, sameCol, nValidMoves, maxDelete, medUtil]
#     print(phi)
    phi += maxCount(state)
    return np.array(phi)

def getQopt(state, action):
    global net
    if isEndState(state): return 0.
    return net.predict([getFeatureVec(state, action)])[0]


# def updateQ(state, action, reward, newState):
# 	Vopt, pi_opt = max((Qopt[(newState, action)], action) for action in actions(newState))
# 	Qopt[(state, action)] = (1-STEP_SIZE)*Qopt[(state, action)] + STEP_SIZE*(reward + DISCOUNT*Vopt)
# 	updated.add(state)
# 	return

def updateWeights(state, action, reward, newState):
    global net
    Vopt, pi_opt = max((getQopt(newState, action), action) for action in actions(newState))
    # weights = weights - STEP_SIZE * (getQopt(state, action) - (reward + DISCOUNT*Vopt)) * getFeatureVec(state, action)
    # for i in range(NFEATURES):
    # 	if weights[i] < 0:
    # 		weights[i] = 0.
    print ("residual:", net.predict([getFeatureVec(state, action)])[0] - (reward + DISCOUNT*Vopt),
    net.partial_fit([getFeatureVec(state, action)], [reward + DISCOUNT*Vopt]))
    return

def aiPlay(grid, sample):
    score = 0
    prevWeights = np.zeros(24, dtype = float)
    for turn in range(NTURNS):
        while True:
            if validMoveExists(grid):
                break
            grid = np.resize((1,NROWS*NCOLS))
            np.random.shuffle(grid)
            grid = np.resize((NROWS, NCOLS))
        turnsLeft = NTURNS - turn
        print ('')
        print ('Turns left:', NTURNS - turn)
        print ('SCORE', score)
        print (grid)
        # print 'generating SARSA...'
        currState = (arrToTuple(grid), turnsLeft)
        # sarsa = [generateSARSA(currState) for i in range(NSARSA)]
        # print 'updating weights'
        # for i in range(NSARSA):
        # 	print i
        # 	for (state, action, reward, newState) in sarsa[i]:
        # 		updateWeights(state, action, reward, newState)
        print ('choosing action...')
        action = None
        if (random.random() < EPSILON):
            print ('choosing random action...')
            action = random.choice(actions(currState))
        else:
            print ('choosing optimal action...')
            Vopt, pi_opt = max((getQopt(currState, action), action) for action in actions(currState))
            action = pi_opt
        print ('switched', action[0], 'and', action[1])
        grid, turnScore = makeSwitch(currState, action)
        score += turnScore
        newState = (arrToTuple(grid), turnsLeft-1)
        print ('updating net')
        updateWeights(currState, action, turnScore, newState)
#         print ('new weights (scaled):',)
#         print (net.coefs_, net.intercepts_)
#         print (net.n_outputs_)
        # print net.n_layers_ ;
        # print net.out_activation_ ;
        # if weights.all() == 0:
        #     scaledWeights = weights
        # else:
        #     scaledWeights = weights/min(weights[i] for i in range(NFEATURES) if weights[i] > 0)
        # print scaledWeights
        # print 'weight diff:', scaledWeights - prevWeights
        # prevWeights = scaledWeights
    print ('')
    print ('Turns left:', 0)
    print (grid)
    print (sample, 'FINAL SCORE', score)
    return score

def main():
    random.seed()
    np.random.seed()
    scoreSum = 0
    for i in range(NUMSAMPLES):
        grid = np.zeros((NROWS, NCOLS), dtype = int)
        grid = initialize(grid)
        score = aiPlay(grid, i+1)
        scoreSum += score
        print (i+1, 'AVERAGE SCORE:', float(scoreSum)/(i+1))
        print ('')
    return

if __name__ == "__main__":
    main()
    


[[2 2 2 2 4 5 1 1]
 [1 1 1 1 4 3 3 5]
 [5 3 1 5 5 3 4 2]
 [3 2 3 3 4 1 4 2]
 [2 2 4 4 3 4 2 1]
 [2 4 4 5 4 4 4 3]
 [3 5 4 5 1 5 5 5]
 [3 1 5 5 1 3 5 2]]

Turns left: 50
SCORE 0
(8, 8)
choosing action...
choosing optimal action...
switched (0, 4) and (0, 5)
updating net
residual: -754.2623719518273 MLPRegressor(hidden_layer_sizes=(10,))

Turns left: 49
SCORE 960
(8, 8)
choosing action...
choosing optimal action...
switched (4, 1) and (4, 2)
updating net


KeyboardInterrupt: 

In [1817]:
import json
import time
readF = {
  "ActionId": -1,
  "PatternId": 0,
  "MoveDirection": "Left", 
  "Pattern": writeF['Pattern']
}

# readF['ActionId'] += 1

with open('GAME\\V1.2.4\\Read.json', 'w') as f:
    json.dump(readF, f)
# time.sleep(0.05)
# readF['ActionId'] = 0
# readF['PatternId'] = 44
# readF['MoveDirection'] = "Bottom"
# # readF['Pattern'] = []
# with open('GAME\\V0.2\\Read.json', 'w') as fp:
#     json.dump(readF, fp)

In [1685]:
with open('GAME\\V1.2.4\\Write.json') as f:
    writeF = json.load(f)


In [1819]:
# with open('GAME\\V1.2.3\\Write.json') as f:
#     writeF = json.load(f)
readF['ActionId'] += 1
readF['PatternId'] = 37
readF['MoveDirection'] = "Bottom"
readF['Pattern'] = writeF['Pattern']
with open('GAME\\V1.2.4\\Read.json', 'w') as fp:
    json.dump(readF, fp)

In [1730]:
import numpy as np
col = 8
row = 8


np.set_printoptions(threshold=10000)
state = []
for icon in writeF['Pattern']:
    lab = icon.split('_')
    icon = lab[1]
    if icon == 'choco':
        state.append(33)
    elif len(lab) == 2:
        state.append(int(icon))
    elif lab[2] == 'extra':
        state.append(int(icon)+8*3)    
    elif lab[3] == 'horiz':
        state.append(int(icon)+8)
    elif lab[3] == 'vert':
        state.append(int(icon)+8*2)

    
# grid = np.array(state).reshape(col,row)
grid
state = np.array(state) - 1
state = to_categorical(state, num_classes=33)
state = state.reshape(state.shape[0]*state.shape[1])
type([1,2,3,] + state.tolist())


list

In [381]:
def actions(state):
    actions = []
    grid = state[0]
    for i in range(NROWS):
        for j in range(NCOLS):
            if isValidMove(grid,(i,j),(i,j+1)):
                coord1 = (i,j)
                coord2 = (i,j+1)
                actions.append((coord1, coord2))
            elif isValidMove(grid,(i,j),(i+1,j)):
                coord1 = (i,j)
                coord2 = (i+1,j)
                actions.append((coord1, coord2))
            if grid[i][j] == 'choco':
                coord1 = (i,j)
                if isValidCoord((i+1,j)):
                    coord2 = (i+1,j)
                    actions.append((coord1, coord2))
                if isValidCoord((i-1,j)):
                    coord2 = (i-1,j)
                    actions.append((coord1, coord2))
                if isValidCoord((i,j+1)):
                    coord2 = (i,j+1)
                    actions.append((coord1, coord2))                
                if isValidCoord((i,j-1)):
                    coord2 = (i,j-1)
                    actions.append((coord1, coord2))
    return actions

def maxCount(state):
    grid = np.array(state[0])
    rowCount = collections.Counter()
    colCount = collections.Counter()
    max_row = []
    max_col = []
    colors = ['01','02','03','04','05','06','07','08','choco']
    for i in range(NROWS):
        for j in range(NCOLS):
            rowCount[(i, grid[i,j])] += 1
        print(rowCount)
        max_row.append(max(rowCount[(i, color)] for color in colors))
        print(max_row)
    for j in range(NCOLS):
        for i in range(NROWS):
            colCount[(j, grid[i,j])] += 1
        max_col.append(max(colCount[(j, color)] for color in colors))
    return max_row + max_col

In [387]:
currState = (arrToTuple(grid), 2)

actions(currState)

[((1, 6), (2, 6)),
 ((2, 5), (2, 6)),
 ((2, 6), (2, 7)),
 ((4, 5), (5, 5)),
 ((6, 6), (7, 6)),
 ((6, 6), (5, 6)),
 ((6, 6), (6, 7)),
 ((6, 6), (6, 5))]

In [1629]:
np.array(writeF['Pattern'])

array(['item_05', 'item_02', 'item_05', 'item_02', 'item_01', 'item_02',
       'item_02', 'item_05', 'item_03', 'item_05', 'item_02', 'item_03',
       'item_05', 'item_02', 'item_01', 'item_05', 'item_04', 'item_02',
       'item_05', 'item_03', 'item_03', 'item_05', 'item_02', 'item_01',
       'item_04', 'item_04', 'item_02', 'item_01', 'item_03', 'item_03',
       'item_01', 'item_05', 'item_05', 'item_02', 'item_05', 'item_01',
       'item_01', 'item_04', 'item_05', 'item_05', 'item_03', 'item_04',
       'item_04', 'item_05', 'item_04', 'item_02', 'item_01', 'item_03',
       'item_03', 'item_04', 'item_05', 'item_05', 'item_02',
       'item_04_extra', 'item_05', 'item_02', 'item_05', 'item_02',
       'item_05', 'item_03', 'item_02', 'item_03_extra', 'item_02',
       'item_03'], dtype='<U13')

In [1635]:
print(grid)
from keras.utils.np_utils import to_categorical
to_categorical(grid, num_classes=6)

[['03' '04' '01' '02' '03' '01' '02' '05']
 ['05' '02' '03' '02' '01' '05' '05' '01']
 ['03' '05' '03' '01' '04' '03' '01' '03']
 ['05' '04' '01' '02' '04' '01' '02' '01']
 ['04' '01' '03' '01' '05' '04' '04' '03']
 ['02' '05' '03' '04' '03' '03' '01' '05']
 ['05' '01' '05' '03' '01' '01' '03' '03']
 ['01' 'choco' '04' '01' '05' '04' '02' '05']]


ValueError: invalid literal for int() with base 10: 'choco'

In [385]:
numValidMoves(currState[0])

4

In [118]:
readF['ActionId']

2

In [112]:
with open('GAME\\V1.2\\Write.json') as f:
    writeF = json.load(f)


writeF['Id']

12

In [1734]:
example = Caculator()

example.add(1,2)

SyntaxError: invalid syntax (<ipython-input-1734-6f6ef1835469>, line 1)